# Site settings
title: AI @ UHasselt
author:
  name: Jan Aerts
  email: jan.aerts@uhasselt.be
description: > # this means to ignore newlines until "baseurl:"
  AI at UHasselt
url: "http://ai.uhasselt.be" # the base hostname & protocol for your site
permalink: /:year/:month/:title
logo: /assets/vda-lab_logo.png

# Build settings
markdown: kramdown

gems:
- jekyll-seo-tag
